import { useMemo, useState } from "react";
import axios from "axios";
import { Link } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import Breadcrumbs from "../../components/Breadcrumbs";
import Button from "../../components/ui/Button";
import Card from "../../components/ui/Card";
import Input from "../../components/ui/Input";
import Loading from "../../components/Loading";
import { toastUI } from "../../components/ui/Toast";
import { useAuth } from "../../hooks/useAuth";
import { generateAiRoadmap } from "../../services/ai";

export default function AiRoadmap() {
  const { user, isLoading } = useAuth();
  const [currentRole, setCurrentRole] = useState("");
  const [targetRole, setTargetRole] = useState("");
  const [roadmap, setRoadmap] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const userSkills = useMemo(() => user?.skills?.map((skill) => skill.name).filter((name) => name.trim() !== "") ?? [], [user?.skills]);

  async function handleGenerate() {
    if (!currentRole.trim() || !targetRole.trim()) {
      toastUI.error("Please fill in both role fields.");
      return;
    }

    setLoading(true);
    setRoadmap(null);

    try {
      const response = await generateAiRoadmap({
        current_role: currentRole.trim(),
        target_role: targetRole.trim(),
        current_skills: userSkills,
      });

      if (!response.success || !response.roadmap) {
        toastUI.error(response.message ?? "Failed to generate roadmap.");
        return;
      }

      setRoadmap(response.roadmap);
      toastUI.success("Roadmap generated successfully.");
    } catch (error) {
      const message = axios.isAxiosError(error) ? error.response?.data?.message : undefined;
      toastUI.error(typeof message === "string" && message.trim() !== "" ? message : "Could not generate roadmap right now.");
    } finally {
      setLoading(false);
    }
  }

  if (isLoading) {
    return <Loading label="Loading AI roadmap..." />;
  }

  if (!user || user.role !== "job_seeker") {
    return (
      <Card title="Job Seeker Access Required" subtitle="This tool is currently available to job seeker accounts only.">
        <Link to="/dashboard" className="btn btn-outline-primary">
          Back to dashboard
        </Link>
      </Card>
    );
  }

  return (
    <div className="vstack gap-3">
      <Breadcrumbs items={[{ label: "Dashboard", to: "/dashboard" }, { label: "AI Career Roadmap" }]} />

      <Card
        title="AI Career Roadmap"
        subtitle="Tell us your starting point and goal, and we will build a focused step-by-step roadmap."
      >
        <div className="row g-3">
          <div className="col-12">
            <Input
              label="Current role or background"
              placeholder="Example: Junior Web Developer"
              value={currentRole}
              onChange={(event) => setCurrentRole(event.target.value)}
            />
          </div>
          <div className="col-12">
            <Input
              label="Target role"
              placeholder="Example: DevOps Engineer"
              value={targetRole}
              onChange={(event) => setTargetRole(event.target.value)}
            />
          </div>
          {userSkills.length > 0 ? (
            <div className="col-12">
              <div className="small text-muted">
                Your saved skills will be included automatically: {userSkills.join(", ")}
              </div>
            </div>
          ) : null}
          <div className="col-12">
            <Button type="button" variant="primary" loading={loading} onClick={() => void handleGenerate()}>
              Generate My Roadmap
            </Button>
          </div>
        </div>
      </Card>

      {roadmap ? (
        <Card title="Your Personalized Roadmap" subtitle="Generated by AI using your profile and target role.">
          <div
            className="bg-light border rounded p-3 mb-0"
            style={{
              overflow: "visible",
              maxHeight: "none",
              height: "auto",
              wordBreak: "break-word",
            }}
          >
            <ReactMarkdown
              components={{
                h1: ({ children }) => <h1 className="h3 mt-3 mb-2">{children}</h1>,
                h2: ({ children }) => <h2 className="h4 mt-3 mb-2">{children}</h2>,
                h3: ({ children }) => <h3 className="h5 mt-3 mb-2">{children}</h3>,
                h4: ({ children }) => <h4 className="h6 mt-3 mb-2">{children}</h4>,
                p: ({ children }) => <p className="mb-2">{children}</p>,
                ul: ({ children }) => <ul className="mb-3 ps-4">{children}</ul>,
                ol: ({ children }) => <ol className="mb-3 ps-4">{children}</ol>,
                li: ({ children }) => <li className="mb-1">{children}</li>,
                strong: ({ children }) => <strong className="fw-semibold">{children}</strong>,
                pre: ({ children }) => <pre className="bg-white border rounded p-3 mb-3 overflow-auto">{children}</pre>,
                code: ({ children }) => <code className="bg-white px-1 rounded">{children}</code>,
              }}
            >
              {roadmap}
            </ReactMarkdown>
          </div>
        </Card>
      ) : null}
    </div>
  );
}
